### ISSUE TITLE
Add span to all functions?

### ISSUE THREAD

**Issue by DHBrett** [codebrick-corp/nestjs-ddtrace#2]
Hey thanks for putting this library together!

I see we can add decorators to individual functions or controllers, but is there a way to automatically add a span for every function in all controllers and services in the project? If not, is there a reason not to? I'd be happy to contribute a PR to add that as an option

**Comment by wokim** [comment]
@DHBrett thanks for the feedback!

The `span` decorator can be applied to every function by applying `span` decorator to the top of each controller and service.

```ts
import { Span } from 'nestjs-ddtrace';

@Injectable()
@Span()
export class BookService {
  async getBooks() { ... }
  async deleteBook(id: string) { ... }
}

@Controller()
@Span()
export class HelloController {
  @Get('/books')
  getBooks() { ... }

  @Delete('/books/:id')
  deleteBooks() { ... }
}
```

However, there is an issue that tracing result becomes too complicated because it is applied to private methods in the class as well. Because of this, we manually apply the decorator to the methods we want.

**Comment by DHBrett** [comment]
@wokim sure that's what we're doing now, but it can be tedious when there are dozens of controllers and services and we don't want to forget to add the tracing to new ones. 

I was hoping for something like
`DatadogTraceModule.forRoot({ controllers: true, services: true })`
Would that be possible? Like I said I'd be happy to contribute :)

**Comment by wokim** [comment]
Sorry for late reply.
It looks a good idea. I will update it soon! (or It would be an honor if you could contribute 😄
